create table users (
  id uuid primary key default gen_random_uuid(),
  telegram_user_id bigint not null unique,
  display_name text not null,
  username text,
  phone_e164 text check (phone_e164 is null or phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  locale app_locale not null default 'uz_cyrl',
  is_blocked boolean not null default false,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table master_profiles (
  user_id uuid primary key references users(id) on delete cascade,
  approval_status master_approval_status not null default 'pending',
  is_active boolean not null default true,
  approved_by uuid references users(id),
  approved_at timestamptz,
  revoked_by uuid references users(id),
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_master_approval_fields check (
    (approval_status = 'approved' and approved_by is not null and approved_at is not null)
    or
    (approval_status <> 'approved')
  )
);

create table admin_profiles (
  user_id uuid primary key references users(id) on delete cascade,
  is_active boolean not null default true,
  granted_by uuid references users(id),
  granted_at timestamptz not null default now(),
  revoked_by uuid references users(id),
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table service_domains (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  name_uz_cyrl text not null,
  name_ru text not null,
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table issue_tags (
  id smallint generated by default as identity primary key,
  domain_id smallint not null references service_domains(id) on delete restrict,
  slug text not null,
  name_uz_cyrl text not null,
  name_ru text not null,
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (domain_id, slug),
  unique (domain_id, id)
);

create table service_requests (
  id uuid primary key default gen_random_uuid(),
  public_code text not null unique,
  requester_id uuid not null references users(id) on delete restrict,

  domain_id smallint not null references service_domains(id) on delete restrict,
  issue_tag_id smallint,
  issue_custom text,

  problem_summary text,
  phone_e164 text check (phone_e164 is null or phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  address_text text,
  landmark_text text,

  urgency urgency_level,
  visit_time_mode visit_time_mode,
  visit_time_at timestamptz,

  consent_share boolean not null default false,
  locale app_locale not null default 'uz_cyrl',
  status request_status not null default 'draft',

  current_dispatch_attempt int not null default 0,
  closed_reason text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint fk_request_issue_tag_domain
    foreign key (domain_id, issue_tag_id)
    references issue_tags(domain_id, id)
    on delete restrict,

  constraint chk_visit_time_consistency check (
    (visit_time_mode is null and visit_time_at is null)
    or (visit_time_mode = 'asap' and visit_time_at is null)
    or (visit_time_mode = 'scheduled' and visit_time_at is not null)
  )
);

create table request_intake_messages (
  id bigserial primary key,
  request_id uuid not null references service_requests(id) on delete cascade,
  sender intake_sender not null,
  message_text text not null,
  field_patch jsonb not null default '{}'::jsonb,
  validation_snapshot jsonb,
  offtopic boolean not null default false,
  abuse boolean not null default false,
  created_at timestamptz not null default now()
);

create table request_attachments (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references service_requests(id) on delete cascade,
  kind text not null check (kind = 'photo'),
  storage_path text not null unique,
  uploaded_by uuid not null references users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table dispatch_records (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references service_requests(id) on delete cascade,
  attempt_no int not null check (attempt_no >= 1),

  telegram_group_id bigint not null,
  telegram_message_id bigint,

  status dispatch_status not null default 'pending_send',
  expires_at timestamptz,

  claimed_by_master_id uuid references users(id) on delete restrict,
  claimed_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (request_id, attempt_no),

  constraint chk_dispatch_claimed_fields check (
    (status = 'claimed' and claimed_by_master_id is not null and claimed_at is not null)
    or
    (status <> 'claimed' and claimed_by_master_id is null and claimed_at is null)
  )
);

create table orders (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null unique references service_requests(id) on delete restrict,
  status order_status not null default 'accepted',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  canceled_at timestamptz
);

create table order_assignments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id) on delete cascade,
  master_id uuid not null references users(id) on delete restrict,
  status assignment_status not null default 'active',
  is_current boolean not null default true,
  assigned_at timestamptz not null default now(),
  ended_at timestamptz,
  end_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint chk_assignment_state check (
    (status = 'active' and is_current = true and ended_at is null)
    or
    (status <> 'active' and is_current = false and ended_at is not null)
  )
);

create table status_history (
  id bigserial primary key,
  entity_type text not null check (entity_type in ('request', 'order', 'dispatch', 'assignment')),
  entity_id uuid not null,
  from_status text,
  to_status text not null,
  actor_user_id uuid references users(id) on delete set null,
  actor_role audit_actor_role not null,
  reason text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table audit_logs (
  id bigserial primary key,
  actor_user_id uuid references users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id uuid,
  meta jsonb not null default '{}'::jsonb,
  ip inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create table webhook_events (
  id bigserial primary key,
  source webhook_source not null default 'telegram',
  external_event_id text not null,
  payload jsonb not null,
  processing_status webhook_processing_status not null default 'received',
  error_text text,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (source, external_event_id)
);

create table idempotency_keys (
  id bigserial primary key,
  scope text not null,
  key text not null,
  request_hash text not null,
  response_code int,
  response_body jsonb,
  created_by_user_id uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  unique (scope, key)
);
